// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {PauseModule} from "./Module/PauseModule.sol";
import {IVibeText} from "./Interface/IVibeText.sol";

contract VibeText is IVibeText, PauseModule {
    address public owner;

    mapping(address => bool) public admins;

    mapping(string => bool) public processedVerifications;

    constructor(address _owner) {
        owner = _owner;
        admins[_owner] = true;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) revert NotOwner();
        _;
    }

    modifier onlyAdmin() {
        if (!admins[msg.sender]) revert NotAdmin();
        _;
    }

    function addAdmin(address _admin) public onlyOwner {
        admins[_admin] = true;
        emit IVibeText.AdminAdded(_admin);
    }

    function removeAdmin(address _admin) public onlyOwner {
        admins[_admin] = false;
        emit IVibeText.AdminRemoved(_admin);
    }

    /**
     * @dev Anyone (users, sponsors, businesses) can fund the protocol treasury directly.
     */
    function fundTreasury() public payable {
        if (msg.value == 0) revert InvalidAmount();
        emit IVibeText.TreasuryFunded(msg.sender, msg.value);
    }

    receive() external payable {
        if (msg.value > 0) {
            emit IVibeText.TreasuryFunded(msg.sender, msg.value);
        }
    }

    /**
     * @dev Called by the Node.js backend (acting as an Admin Oracle) when a user successfully
     *      provides a high-quality community note / authenticity validation.
     * @param _validator The wallet address of the user who rated vibes on the frontend.
     * @param _amount The micro-reward in native tokens (e.g. 0.05 BOT).
     * @param _verificationId A unique ID generated by the DB (e.g., MongoDB `_id` of the rating).
     */
    function rewardValidator(address _validator, uint256 _amount, string memory _verificationId) public onlyAdmin whenNotPaused {
        if (_validator == address(0)) revert IVibeText.AddressZero();
        if (_amount == 0) revert InvalidAmount();
        if (address(this).balance < _amount) revert TreasuryDepleted();
        if (processedVerifications[_verificationId]) revert AlreadyProcessed();

        processedVerifications[_verificationId] = true;

        (bool success, ) = payable(_validator).call{value: _amount}("");
        if (!success) revert TransferFailed();

        emit IVibeText.ValidatorRewarded(_validator, _amount, _verificationId);
    }

    function withdraw(uint256 _amount) public onlyOwner {
        if (address(this).balance < _amount) revert TreasuryDepleted();

        (bool success, ) = payable(owner).call{value: _amount}("");
        if (!success) revert TransferFailed();

        emit IVibeText.Withdrawn(owner, _amount);
    }

    function pause() public onlyOwner {
        _pause();
    }

    function unpause() public onlyOwner {
        _unpause();
    }
}
